// Mocks generated by Mockito 5.4.2 from annotations
// in simple_flutter/test/features/feed/bloc/feed_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:simple_flutter/core/model/range.dart' as _i4;
import 'package:simple_flutter/domain/entity/movie_entity.dart' as _i7;
import 'package:simple_flutter/domain/use_case/get_movies_page_range_use_case.dart'
    as _i2;
import 'package:simple_flutter/features/feed/bloc/feed_bloc.dart' as _i5;
import 'package:simple_flutter/features/feed/widgets/feed_list.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetPageRangeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPageRangeUseCase extends _i1.Mock
    implements _i2.GetPageRangeUseCase {
  @override
  _i3.Stream<_i2.GetPageRangeResult> getPageRange(
          {required _i4.Range? range}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPageRange,
          [],
          {#range: range},
        ),
        returnValue: _i3.Stream<_i2.GetPageRangeResult>.empty(),
        returnValueForMissingStub: _i3.Stream<_i2.GetPageRangeResult>.empty(),
      ) as _i3.Stream<_i2.GetPageRangeResult>);
}

/// A class which mocks [FeedUiItemsMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedUiItemsMapper extends _i1.Mock implements _i5.FeedUiItemsMapper {
  @override
  List<_i6.FeedUiItem> generateItems({required List<_i7.Page>? pages}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateItems,
          [],
          {#pages: pages},
        ),
        returnValue: <_i6.FeedUiItem>[],
        returnValueForMissingStub: <_i6.FeedUiItem>[],
      ) as List<_i6.FeedUiItem>);
  @override
  List<_i6.FeedUiItem> generateErrorItems({required List<_i7.Page>? pages}) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateErrorItems,
          [],
          {#pages: pages},
        ),
        returnValue: <_i6.FeedUiItem>[],
        returnValueForMissingStub: <_i6.FeedUiItem>[],
      ) as List<_i6.FeedUiItem>);
}
