// Mocks generated by Mockito 5.4.2 from annotations
// in simple_flutter/test/domain/use_case/get_page_range_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:simple_flutter/core/model/range.dart' as _i7;
import 'package:simple_flutter/domain/entity/movie_entity.dart' as _i6;
import 'package:simple_flutter/domain/repository/movie_repository.dart' as _i2;
import 'package:simple_flutter/domain/use_case/get_movies_page_range_use_case.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i2.MovieRepository {
  @override
  _i3.Future<_i4.Either<_i5.GetPageError, List<_i6.Page>>> getMoviePageRange(
          {required _i7.Range? range}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoviePageRange,
          [],
          {#range: range},
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.GetPageError, List<_i6.Page>>>.value(
                _i8.dummyValue<_i4.Either<_i5.GetPageError, List<_i6.Page>>>(
          this,
          Invocation.method(
            #getMoviePageRange,
            [],
            {#range: range},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.GetPageError, List<_i6.Page>>>.value(
                _i8.dummyValue<_i4.Either<_i5.GetPageError, List<_i6.Page>>>(
          this,
          Invocation.method(
            #getMoviePageRange,
            [],
            {#range: range},
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.GetPageError, List<_i6.Page>>>);
}
